# Generated by Django 2.2.4 on 2019-08-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('questions', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('offer', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unsure', 'Not Sure')], max_length=10)),
                ('racial_group', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=20)),
                ('employment_year', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_submission', to='home.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_interview', to='home.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_review', to='home.Review')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_submission', to='home.Submission'),
        ),
    ]
